//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joole.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeFilter
    {
        public int PropertyID { get; set; }
        public int SubCategoryID { get; set; }
        public string TypeName { get; set; }
        public string TypeOptions { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
//Hank DevBranch Test
//Haolun DevBranch Tests
//Legend Test